name: firebase_auth_example
description: Demonstrates how to use the firebase_auth plugin.
author: Flutter Team <flutter-dev@googlegroups.com>

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  firebase_auth: ^1.1.4
  firebase_core: ^ 1.1.1  
  firebase_dynamic_links: ^2.0.3
  flutter:
    sdk: flutter
  flutter_signin_button: ^1.0.0
  google_sign_in: ^5.0.0-nullsafety

dependency_overrides:
  firebase_auth: ^1.1.4                                                   
  firebase_auth_platform_interface: ^4.2.2                                
  firebase_auth_web: ^1.1.2                                               
  firebase_core: ^1.1.1                                                   
  firebase_core_platform_interface: ^4.0.1                                
  firebase_core_web: ^1.0.3                                               
  firebase_dynamic_links: ^2.0.3      


dev_dependencies:
  drive: 0.1.0
  flutter_driver:
    sdk: flutter
  http: ^0.13.0
  test: any

flutter:
  uses-material-design: true
