name: etumedbussiness
description: Demonstrates how to use the firebase_auth plugin.
author: Flutter Team <flutter-dev@googlegroups.com>

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  firebase_auth: ^1.1.4
  firebase_core: ^1.1.1  
  firebase_dynamic_links: ^2.0.3
  flutter:
    sdk: flutter
  flutter_signin_button: ^1.0.0
  google_sign_in: ^5.0.0-nullsafety
  cloud_firestore_platform_interface: ^5.0.1
  cloud_firestore_web: ^2.0.1
  firebase_core_platform_interface: ^4.0.1
  meta: ^1.3.0
  cloud_firestore: ^2.1.0
  firebase_messaging: ^9.1.4
  google_fonts: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  drive: 0.1.0
  flutter_driver:
    sdk: flutter
  http: ^0.13.0
  test: any

flutter:
  uses-material-design: true
  assets:
    - 1.jpg
